Updated readme
TaskarCenterAtUW/TDEI-python-gtfs-pathways-validation pull request #16
Opened 2023-06-08 12:36 UTC by sujata-m

Updated README.md for how to run test cases

2023-06-08 13:44 UTC, susrisha commented on README.md
> +   # To run all th unit test cases
To run all _the_

2023-06-08 13:45 UTC, susrisha commented on README.md
> +1. Set up the python env locally, see [here](#how-to-setup-aand-build)
two `a` characters for `and`

2023-06-08 13:45 UTC, susrisha requested changes
one minor typo

2023-06-18 13:34 UTC, sureshgaussian requested changes
I see that 'fail_riles_1.zip' and 'success_1_all_attr.zip' are under src/assets folder. As far as I know these two are zip files for tests. Shouldn't they be under tests folder? They unnecessarily take up space in the docker container.

2023-06-20 14:14 UTC, susrisha approved these changes

2023-06-20 14:26 UTC, sureshgaussian approved these changes
Tested the code locally and it passes

2023-06-20 14:27 UTC, merged